### ISSUE TITLE
代码更改后，重新编译，浏览器不自动刷新

### ISSUE THREAD

**Issue by rainwind132** [Bigerfe/koa-react-ssr#4]
我将你的代码下载到本地后，安装好依赖，npm run dev，然后更改APP文件下的index.js，改一下标题后，浏览器不自动刷新，请问这个怎么解决？

**Comment by zzzjesse** [comment]
具体是什么环境，使用的是那个分支？

**Comment by zzzjesse** [comment]
目前已应用HMR
